### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by neerajsingh0101**

### CODE REVIEW

**Comment by natew** [comment]
Actually you should just have to run:

`reapp run` or `reapp run -d` if you want debugging. No need for the -V command.

**Comment by neerajsingh0101** [comment]
I posted it so that when user shows the log we get to see the log version.

**Comment by natew** [comment]
Good point, forgot -d doesn't do this automatically. Should add that as well.

**Comment by neerajsingh0101** [comment]
Thanks for merging.

Could you please quickly look into https://github.com/reapp/hacker-news-app/issues/8 .I'm sure I'm missing a step or something. All I did was npm install.

**Pull request merged**
